const texts = [
  "The sun dipped below the horizon, painting the sky in hues of orange and pink. A gentle breeze rustled the leaves, carrying the scent of jasmine through the air. Lena sat on the wooden bench, her fingers tracing patterns on the worn-out book cover. She had always loved the quiet evenings, a perfect escape from the day’s chaos. Tonight, however, something felt different, as if the air carried an unspoken secret. A stray cat approached, its green eyes reflecting the dim streetlight’s glow. It purred softly, rubbing against Lena’s leg before curling up beside her. She smiled, momentarily forgetting the letter folded in her pocket. The words on the paper had haunted her all day, a message from an old friend. It spoke of forgotten promises and a reunion she wasn’t sure she was ready for. Memories flooded back—laughter, shared dreams, and the painful silence that followed their last meeting. Lena sighed, unfolding the letter once more, her heart pounding. The cat stirred as she read the final words, ‘Meet me at the bridge.’ She hesitated but felt an undeniable pull. Rising from the bench, she tucked the letter into her coat pocket and walked into the night.",

  "The old bookstore smelled of parchment and ink, its dim lighting casting long shadows between the shelves. Oliver ran his fingers over the spines, pausing at a leather-bound book with intricate gold lettering. He carefully pulled it out, feeling the weight of its history. As he flipped through the fragile pages, a note slipped out and fluttered to the floor. Curious, he picked it up and read the faded ink: 'The key is beneath the clock.' He glanced around. At the far end of the store, an ancient grandfather clock ticked softly. Approaching it, his pulse quickened. He knelt down, sliding his fingers under the base until he felt something cold. A tiny brass key. Excitement surged through him. But where was the lock? He turned the key over, noticing a symbol that matched the book’s cover. Carefully, he examined the inside of the book, pressing against the back cover. A small compartment popped open, revealing a folded map. His heart pounded. A hidden treasure? A forgotten secret? The possibilities overwhelmed him. With the key in hand, he knew this was only the beginning of a new adventure. He closed the book, tucked the map inside, and walked out with purpose.",

  "The storm raged outside, rattling the windows of the tiny cabin. Ava curled up by the fireplace, sipping warm tea, her book open on her lap. Thunder rumbled in the distance, a deep, rolling sound that made her shiver. The cabin had been her sanctuary for years, a place of peace away from the city’s noise. But tonight, the howling wind carried an eerie whisper. She dismissed it as her imagination, but when a soft knock echoed through the room, her breath hitched. Who could be here in this storm? She hesitated, then stood, heart pounding, and approached the door. Slowly, she unlatched it. A man stood there, drenched, his dark eyes pleading. 'I got lost in the storm,' he said between ragged breaths. Ava hesitated before stepping aside, letting him in. He shook off his coat, his gaze scanning the room. 'Thank you,' he murmured, but something in his tone made her uneasy. The fire crackled, casting flickering shadows on the walls. 'Do you live here alone?' he asked, his voice almost too casual. Ava’s grip tightened on her mug. A chill ran down her spine. The storm outside was nothing compared to the danger that had just walked in.",

  "The train whistled, steam billowing into the night air as Amelia stepped onto the platform. She gripped her suitcase, her heart heavy. This was her last chance to leave, to start over. The city behind her held memories she couldn’t bear to relive. But just as she turned toward the train, a voice called her name. She froze. It had been years since she’d heard that voice. Slowly, she turned to see Daniel standing there, breathless. 'You’re really leaving?' he asked. She nodded, gripping the handle of her suitcase tighter. He took a step closer. 'You don’t have to go.' She swallowed hard. 'Yes, I do.' The train doors hissed open. Her future was waiting. Daniel’s eyes searched hers, filled with words he couldn’t say. The past tugged at her heart, but she forced herself to move. One step. Two. She climbed onto the train, refusing to look back. The doors closed, sealing her decision. As the train pulled away, she watched the platform disappear into the distance. Regret or relief—she wasn’t sure which she felt. But one thing was certain. There was no turning back now.",

  "The lighthouse stood tall against the dark sea, its beam cutting through the thick fog. Captain Elias watched from his ship, gripping the railing. The storm had forced them off course, and land was their only salvation. 'Steady!' he called to his crew. The ship groaned as waves crashed against its hull. Through the mist, the lighthouse’s light flickered. Something wasn’t right. 'That’s not the signal we know,' his first mate muttered. Elias frowned. The lighthouse keeper had always been precise, never changing the rhythm. 'Something’s wrong,' he agreed. As they neared the shore, a sudden realization chilled him. The flickering light wasn’t a signal—it was a warning. 'Turn the ship around!' he shouted, but it was too late. A jagged reef loomed ahead, barely visible beneath the waves. The ship lurched as the hull scraped against the rocks. Panic surged through the crew. Elias clenched his jaw. If this was a trap, someone wanted them wrecked. But why? As the storm raged, the answer remained hidden in the shadows of the lighthouse. And Elias knew they were running out of time.",
  
  "Sophia ran through the forest, her breath coming in short gasps. The letter in her hand burned with the weight of its message. A secret she had never expected. She needed to find him before it was too late. The trees loomed tall, their branches whispering in the night breeze. She stumbled on a root but caught herself, pressing on. The old bridge was just ahead. Would he be there? As she reached it, the air felt thick with anticipation. A shadow moved. 'You came,' a voice said. She froze. It was him. The man from the letter. 'We don’t have much time,' he continued, handing her a small package wrapped in cloth. Sophia hesitated. 'What is this?' He met her gaze. 'The truth.' The wind howled as she slowly unwrapped the package, revealing an old pocket watch. It was identical to the one her father had always carried. A chill ran through her. 'How did you get this?' she whispered. He took a deep breath. 'Because he left it for you. And you need to know why.' Sophia clenched the watch in her palm, realizing her journey was only beginning.",

  "James traced the map with his finger. X marked the spot, but something felt off. The ruins had been untouched for centuries. Why was there a fresh footprint in the dust? He adjusted his hat, scanning the crumbling stone walls. The stories spoke of treasure hidden deep within, but no one had ever returned to confirm it. Taking a cautious step forward, the ground shifted beneath him. He barely had time to react before he tumbled down a hidden shaft. Dust swirled as he hit the floor, coughing as he pushed himself up. A torch flickered ahead. Someone else was here. He held his breath, pressing against the cool stone. Footsteps echoed through the chamber. Then, a voice—low, amused. 'I was wondering when you'd arrive.' James turned, eyes widening. It was her. The rival explorer who had always been one step ahead. She smirked, tossing a coin between her fingers. 'Shall we find the treasure together, or do you want to play hero?' James exhaled, knowing he had no choice. 'Let's find it.' As they stepped forward, the walls groaned. The temple was waking up.",

  "Emma closed the diary, her fingers trembling. Her grandmother’s handwriting spoke of a lost love and a promise made under the old oak tree. Could he still be waiting after all these years? The thought was impossible, yet she couldn’t ignore the pull in her chest. The diary had been tucked away in the attic, its pages yellowed with time. Flipping through it again, she found an address scrawled at the bottom of the last page. That night, under the glow of the streetlamps, she found herself standing before a tiny cottage. Her heart pounded as she knocked. After a moment, the door creaked open. An old man stood there, his eyes widening as he took her in. 'You look just like her,' he whispered. Emma swallowed hard. 'Did you know my grandmother?' His gaze softened. 'I loved her.' The wind rustled the trees as she stepped inside, the scent of old books and memories wrapping around her. She had come searching for a story, but she was about to uncover a legacy of love that had never truly faded.",

  "The hotel room door creaked open. Ethan froze. He had locked it before bed. The curtains billowed though the windows were shut. Someone had been here. His pulse quickened as he reached for the bedside lamp, casting long shadows across the room. A faint outline of footprints trailed toward the closet. Taking a deep breath, he approached. The door groaned as he pulled it open—empty. But something felt wrong. As he turned back to the bed, a whisper brushed against his ear. 'You shouldn’t have come.' His blood ran cold. The room fell silent again, the only sound his racing heartbeat. He grabbed his bag and yanked the door open, stepping into the dimly lit hallway. The air felt heavier than before. He pressed the elevator button, glancing over his shoulder. The room key in his hand was ice cold. As the elevator doors opened, a figure in the distance watched him. Ethan swallowed hard, knowing this wasn’t over. The past had found him. And it wasn’t ready to let go.",

  "The clock struck midnight as Mia stepped onto the bridge. The note had said to meet here. But the bridge was empty. Only the wind answered her. She clutched the letter, her heart pounding. Had it been a mistake? A cruel joke? The river below rippled, reflecting the pale moonlight. She turned to leave when a whisper carried through the air. 'You came.' She spun around, eyes searching. A figure emerged from the shadows, his coat billowing in the night breeze. 'I didn’t think you’d remember,' he said, his voice laced with something unreadable. Mia swallowed hard. 'I never forgot.' He stepped closer, holding out a small, silver locket. 'Then you know why I called you here.' Her fingers trembled as she took it, the memories rushing back. The past had been buried for years, but tonight, under the moonlit sky, it was finally coming to light. And Mia wasn’t sure she was ready for the truth.",

];

export default texts;
